spring:
  application:
    name: zuul-server

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: true
    instance:
      perfer-ip-address: true

zuul:
  routes:
    client-a:
      path: /client/**
      serviceId: client-a